### ISSUE TITLE
v0.8.1 Entry Point Not Found - Windows XP

### ISSUE THREAD

**Issue by tesbal** [Serosis/UQM-MegaMod#98]
UrQuanMasters.exe will not launch with error: "Entry Point Not Found, The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll." GetTickCount64 does not exist in WindowsXP

If XP support is never intended the flag _WIN32_WINNT 0x0501 can be set to prevent it from launching.

**Comment by Serosis** [comment]
Would be more appropriate to list this on Vanilla UQM's issues page.

Also you'd have to tell me exactly where to put `_WIN32_WINNT 0x0501`
